config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/about" => "pages#about"
  get "/hygiene" => "pages#hygiene"
  get "/features" => "pages#features"

  resources :cooks do
    resources :dishes, except: [:index]
  end

  resource :cart, only: [:show, :destroy]

  resources :orders, only: [:show, :new, :create]

  resources :order_items, only: [:create, :update, :destroy] do
    member do
      post 'increment'
      post 'decrement'
    end
  end

end

app/models/cook.rb
class Cook < ApplicationRecord

  has_attachment :avatar

  belongs_to :user

  has_many :dishes, dependent: :destroy

  has_many :cook_specialities, dependent: :destroy
  has_many :specialities, through: :cook_specialities
  accepts_nested_attributes_for :cook_specialities, allow_destroy: true
  accepts_nested_attributes_for :specialities

  has_many :cook_places, dependent: :destroy
  has_many :places, through: :cook_places
  accepts_nested_attributes_for :cook_places, allow_destroy: true
  accepts_nested_attributes_for :places

  validates :user, presence: true
  validates :age, :bio, presence: true
  validates :terms_of_service, acceptance: true

  validate :validate_specialities
  validate :validate_places

  private

    def validate_specialities
      if specialities.size > 2
        errors.add(:Spécialités, "limitées à 2")
      end
    end

    def validate_places
      if places.size > 3
        errors.add(:Adresses, "limitées à 3")
      end
    end

end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController

    skip_before_action :authenticate_user!, only: [:index, :show]

    before_action :set_cook, only: [:show, :edit, :update, :destroy]

    before_action :set_dish_available, only: [:index]

    def index
      @cooks = []
      @places = []
      places = []
        if params[:location]
          nearby_places = Place.near(params[:location], 1)
          @dishes.each do |dish|
          places << dish.cook.places.active.with_coordinates
          end
          places.flatten!
          @places = nearby_places & places
          @places.each do |place|
            @cooks << place.cooks
          end
          @cooks = @cooks.flatten!
        else
          @dishes.each do |dish|
            @cooks << dish.cook
          end
          @cooks = @cooks.uniq
          @cooks.each do |cook|
            @places << cook.places.active.with_coordinates
          end
          @places.flatten!
        end

      @hash = Gmaps4rails.build_markers(@places) do |place, marker|
        marker.lat place.latitude
        marker.lng place.longitude
        marker.infowindow render_to_string(partial: "/cooks/map_box", locals: { place: place })
      end

    end

    def show
      @dishes = @cook.dishes.order(updated_at: :asc)

      @specialities = @cook.specialities
      @places = @cook.places

      # Orders received and users concerned
      @orders_r = Order.joins(:dishes).where(dishes: { cook_id: @cook.id } ).order(created_at: :desc)
      #@orders_r.each do |o_r|
        #@user = User.find_by(email: o_r.email)
      #end

      # Total cagnotte
      @credit = @orders_r.sum { |order| order.in_the_pocket }

      # Orders placed and cooks concerned
      @orders_p = Order.where(email: @cook.user.email).order(created_at: :desc)

    end

    def new
      @cook = Cook.new

      @cook_places = @cook.cook_places.build
      @place = @cook_places.build_place

      @cook_specialities = @cook.cook_specialities.build
      @speciality = @cook_specialities.build_speciality
    end

    def create
      @cook = Cook.new(cook_params)
      @cook.user_id = current_user.id
      respond_to do |format|
        if @cook.save
          format.html { redirect_to cook_url(@cook), notice: "Votre profil a bien été créé" }
        else
          format.html { render :new }
        end
      end
    end

    def edit
    end

    def update
      @places = @cook.places
      if @cook.user == current_user
        if @cook.update(cook_params)
          redirect_to cook_url(@cook), notice: "Votre profil a bien été modifié"
        else
          render :edit
        end
      else
        flash[:alert] = "Action impossible, ce n'est pas votre profil !"
        render :edit
      end
    end

    def destroy
      if @cook.user == current_user
        @cook.destroy
        redirect_to cooks_url, notice: "Votre profil a bien été supprimé"
      else
        flash[:alert] = "Action impossible, ce n'est pas votre profil !"
        redirect_to cooks_url
      end
    end

    private

      def set_cook
        @cook = Cook.find(params[:id])
      end

      def set_dish_available
        @dishes = Dish.available
      end

      def cook_params
        params.require(:cook).permit( :user_id, :age, :bio, :avatar, :terms_of_service,
          cook_specialities_attributes: [:id, :speciality_id, :_destroy,
            speciality_attributes: [:id, :_destroy, :name, :level]],
          cook_places_attributes: [:id, :place_id, :_destroy,
            place_attributes: [:id, :_destroy, :full_address, :zip_code, :city, :kind_of_place, :comments, :active]])
      end

end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/views/cooks/_add_to_cart.html.erb
<%= link_to order_items_path(dish_id: dish.id), remote: true, method: :post do %>
  <i class="fas fa-shopping-basket"></i>
<% end %>

app/views/cooks/_addto_cart_show.html.erb
<%= link_to order_items_path(quantity: 1, dish_id: dish.id), remote: true, method: :post do %>
  <i class="fa fa-shopping-basket"></i>
<% end %>

app/views/cooks/_cooks_cards.html.erb
<div class="col-md-12 col-lg-6">
  <div class="cook_card">
    <div class="cook_card-category">
      <% cook.specialities.each do |speciality| %>
        <%= speciality.name %> <span class="label label-warning"><%= speciality.level %></span><br>
      <% end %>
    </div>

    <div class="cook_card-description">
      <h2><%= cook.user.first_name %></h2>

      <p>
        <% cook.places.each do |place| %>
          <% if place.active %>
            <%= place.full_address %><br>
            <%= "#{place.zip_code} #{place.city}" %>
          <% end %>
          <% if params[:location] %>
            <span class="label label-warning"><%= number_to_human(place.distance_from(params[:location]), units: {unit: "Km", mili: "m"}) %></span>
          <% end %>
        <% end %><br>
      </p>

      <% if cook.dishes.empty? %>
        <p>
          Aucune popote en route...
        </p>
      <% else %>
        <p>
          <%= "#{cook.dishes.available.size} #{pluralize_with_0('popote', cook.dishes.available.size)}" %>
        </p>
      <% end %>
    </div>

    <% if cook.user.picture? && cook.avatar? %>
      <%= cl_image_tag cook.avatar.path, quality: 80, fetch_format: :auto, crop: :thumb, gravity: :face, class:"cook_card-user avatar-large" %>
    <% elsif !cook.user.picture? && cook.avatar? %>
    <%= cl_image_tag cook.avatar.path, quality: 80, fetch_format: :auto, crop: :thumb, gravity: :face, class:"cook_card-user avatar-large" %>
    <% elsif cook.user.picture? && !cook.avatar? %>
      <%= image_tag cook.user.picture, class:"cook_card-user avatar-large" %>
    <% else %>
      <%= image_tag "chef.jpg", class:"cook_card-user avatar-large" %>
    <% end %>

    <%= link_to "", cook_path(cook), class: "cook_card-link" %>
  </div>
</div>

app/views/cooks/_countdown.html.erb
<span id="date" class="finalDate-<%=dish.id%> label label-primary"></span>

<% content_for(:after_js) do %>
  <script type="text/javascript">
    $(document).ready(function () {

      $('.finalDate-<%=dish.id%>').countdown("<%= dish.exp_date %>")
      .on('update.countdown', function(event) {
        var format = '%H hr %M min %S';
        if(event.offset.totalDays > 0) {
          format = '%-d jour%!d ' + format;
        }
        if(event.offset.weeks > 0) {
          format = '%-w semaine%!w ' + format;
        }
        $(this).html(event.strftime(format));
      })
      .on('finish.countdown', function(event) {
        $(this).html('Temps écoulé')
          .parent().addClass('disabled');
      });

    });
  </script>
<% end %>

app/views/cooks/_map_box.html.erb
<% place.cooks.each do |cook| %>
  <div class="map_box" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://source.unsplash.com/330x175/?food,cook');">
    <div class="map_box-category">
      <% cook.specialities.each do |speciality| %>
        <%= speciality.name %> <span class="label label-warning"><%= speciality.level %></span><br>
      <% end %>
    </div>

    <div class="map_box-description">
      <h2><%= cook.user.first_name %></h2>
      <p>
        <% cook.places.each do |place| %>
          <% if place.active %>
            <%= place.full_address %><br>
            <%= "#{place.zip_code} #{place.city}" %>
          <% end %>
          <% if params[:location] %>
            <span class="label label-warning"><%= number_to_human(place.distance_from(params[:location]), units: {unit: "Km", mili: "m"}) %></span>
          <% end %>
        <% end %><br>
      </p>
      <%= "#{cook.dishes.size} #{pluralize_with_0('popote', cook.dishes.size)}" %>
    </div>

    <% if cook.user.picture? && cook.avatar? %>
      <%= cl_image_tag cook.avatar.path, quality: 80, fetch_format: :auto, crop: :thumb, gravity: :face, class:"cook_card-user avatar-large" %>
    <% elsif !cook.user.picture? && cook.avatar? %>
    <%= cl_image_tag cook.avatar.path, quality: 80, fetch_format: :auto, crop: :thumb, gravity: :face, class:"cook_card-user avatar-large" %>
    <% elsif cook.user.picture? && !cook.avatar? %>
      <%= image_tag cook.user.picture, class:"cook_card-user avatar-large" %>
    <% else %>
      <%= image_tag "chef.jpg", class:"cook_card-user avatar-large" %>
    <% end %>

    <%= link_to "", cook_path(cook), class: "map_box-link" %>
  </div>
<% end %>

app/views/cooks/_o_po_i.html.erb
<div class="cart">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <div class="dish">

        <div class='dish-upvote'>
          <div class='dish_order-count'><%= o_po_i.quantity %></div>
        </div>

        <% if dish.photos? %>
          <%= cl_image_tag dish.photos.first.path, height: 117, width: 175, quality: 80, fetch_format: :auto, crop: :fill, class:"dish-image hidden-xs" %>
        <% else %>
          <%= image_tag "tupperwares.jpg", alt:"Popote", class:"dish-image hidden-xs" %>
        <% end %>

        <div class='dish-body'>
          <h3><%= dish.name %></h3>
          <h5>
            Sous-total : <%= number_to_currency(o_po_i.total_price, locale: :fr) %>
          </h5>
        </div>

        <div class="dish-details">
          <h5>Rendez-vous</h5>
          <p>
            <% dish.cook.places.each do |place| %>
              <% if place.active %>
                <%= place.full_address %><br>
                <%= "#{place.zip_code} #{place.city}" %><br>
              <% end %>
            <% end %>
            <span class="label label-primary"><%= dish.collect_date.strftime('%d/%m/%Y %H:%M') %></span>
          </p>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/cooks/_oi_p.html.erb
<div class="cart">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <div class="dish">

        <div class='dish-upvote'>
          <div class='dish_order-count'><%= order_item.quantity %></div>
        </div>

        <% if dish.photos? %>
          <%= cl_image_tag dish.photos.first.path, height: 117, width: 175, quality: 80, fetch_format: :auto, crop: :fill, class:"dish-image hidden-xs" %>
        <% else %>
          <%= image_tag "tupperwares.jpg", alt:"Popote", class:"dish-image hidden-xs" %>
        <% end %>

        <div class='dish-body'>
          <h3><%= dish.name %></h3>
          <h5>
            Sous-total : <%= number_to_currency(order_item.total_price, locale: :fr) %>
          </h5>
        </div>

        <div class="dish-details">
          <h5>Rendez-vous</h5>
          <p>
            <% dish.cook.places.each do |place| %>
              <% if place.active %>
                <%= place.full_address %><br>
                <%= "#{place.zip_code} #{place.city}" %><br>
              <% end %>
            <% end %>
            <span class="label label-primary"><%= dish.collect_date.strftime('%d/%m/%Y %H:%M') %></span>
          </p>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/cooks/_oi_r.html.erb
<div class="cart">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <div class="dish">

        <div class='dish-upvote'>
          <div class='dish_order-count'><%= order_item.quantity %></div>
        </div>

        <% if dish.photos? %>
          <%= cl_image_tag dish.photos.first.path, height: 117, width: 175, quality: 80, fetch_format: :auto, crop: :fill, class:"dish-image hidden-xs" %>
        <% else %>
          <%= image_tag "tupperwares.jpg", alt:"Popote", class:"dish-image hidden-xs" %>
        <% end %>

        <div class='dish-body'>
          <h3><%= dish.name %></h3>
          <h5>
            Sous-total : <%= number_to_currency(order_item.total_price, locale: :fr) %>
          </h5>
        </div>

        <div class="dish-details">
          <h5>Rendez-vous</h5>
          <p>
            <% dish.cook.places.each do |place| %>
              <% if place.active %>
                <%= place.full_address %><br>
                <%= "#{place.zip_code} #{place.city}" %><br>
              <% end %>
            <% end %>
            <span class="label label-primary"><%= dish.collect_date.strftime('%d/%m/%Y %H:%M') %></span>
          </p>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/cooks/_place.html.erb
<fieldset class="item">
  <div class="duplicatable_nested_form_two">
    <hr />
    <%=p.input :kind_of_place, label: 'Type de lieu', collection: ["Domicile", "Bureaux/Agence", "Commerce/Restaurant", "Parc/Lieu public"], as: :select %>
    <%=p.input :full_address, label: 'N° / Voie', input_html: { class: 'cook_address' }, placeholder: ""  %>
    <%=p.input :zip_code , label: 'Code Postal', input_html: { class: 'cook_zip_code' }  %>
    <%=p.input :city, label: 'Ville', input_html: { class: 'cook_city' }  %>
    <%=p.input :active, inline_label: "Définir comme votre adresse active" %>
    <%=p.input :comments, label: 'Indications (transmises en cas de commande)', placeholder: "Code porte, 'S'adresser à la loge', 'Récupérer au café d'en face', 'Demander untel à l'accueil', 'Parc entrée Ouest'..." %>

    <%= link_to 'Supprimer', '', remote: true, class: "destroy_duplicate_nested_form_two btn btn-popote-bis" %>

    <%= p.input :id, as: :hidden %>
  </div>
</fieldset>

app/views/cooks/_speciality.html.erb
<fieldset class="item">
  <div class="duplicatable_nested_form_one">
    <hr />
    <%=s.input :name, label: 'Spécialité', collection: ["Gastronomique", "Terroir & Famille", "Cuisines du monde", "Bio & Diététique"], as: :select %>
    <%=s.input :level, label: 'Niveau', collection: ["Top Chef", "Avancé", "Amateur", "Débutant"], as: :select %>
    <%= link_to 'Supprimer', '', remote: true, class: "destroy_duplicate_nested_form_one btn btn-popote-bis" %>

    <%= s.input :id, as: :hidden %>
  </div>
</fieldset>

app/views/cooks/edit.html.erb
<div class="container padded text-center">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Modifier mon profil</h1>
      <%= render "form" %>

      <p>&nbsp</p>

      <p>
        <%= link_to "Supprimer mon profil", cook_path(@cook), method: :delete, data: {confirm: 'Êtes-vous sûr de vouloir supprimer votre profil ?'}, class: "btn btn-danger" %>
      </p>
    </div>
  </div>
</div>

app/views/cooks/new.html.erb
<div class="container padded text-center">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h2 class="text-center">Partagez votre cuisine maison et gagnez un peu d'oseille</h2>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/cooks/show.html.erb
<div class="flash"></div>

<div class="tabs" role="tablist">
  <a class="tab" role="presentation" href="#cook-profile" aria-controls="cook-profile" role="tab" data-toggle="tab">
    <h3>Profil</h3>
    <p></p>
  </a>
  <a class="tab" role="presentation" href="#cook-dishes" aria-controls="cook-dishes" role="tab" data-toggle="tab">
    <h3>
      <% if @dishes.empty? %>
        Aucune popote pour le moment...
      <% else %>
        <%= "#{ pluralize_with_0('Popote', @cook.dishes.available.size) } " %><br>
        <%= "#{ @dishes.available.size } " %>
      <% end %>
    </h3>
    <p></p>
  </a>
  <% if @cook.user == current_user %>
    <a class="tab" role="presentation" href="#orders_r" aria-controls="orders_r" role="tab" data-toggle="tab">
      <h3>
        <% if @orders_r.empty? %>
          Aucune commande reçue...
        <% else %>
          <%= "#{ pluralize_with_0('Commande', @orders_r.size) } #{ pluralize_with_0('reçue', @orders_r.size) } " %><br>
          <%= "#{ @orders_r.size } " %>
        <% end %>
      </h3>
      <p></p>
    </a>
    <a class="tab" role="presentation" href="#orders_p" aria-controls="orders_p" role="tab" data-toggle="tab">
      <h3>
        <% if @orders_p.empty? %>
          Aucune commande passée...
        <% else %>
          <%= "#{ pluralize_with_0('Commande', @orders_p.size) } #{ pluralize_with_0('passée', @orders_p.size) } " %><br>
          <%= "#{@orders_p.size} " %>
        <% end %>
      </h3>
      <p></p>
    </a>
  <% end %>
</div>

<div class="tab-content">

  <div role="tabpanel" class="tab-pane" id="cook-profile">
    <div id= "cook-profile" class="cook-description container">

      <% if @cook.user == current_user %>
        <p class="text-left">
          <%= link_to "Modifier mon profil", edit_cook_path(@cook), class: "btn btn-popote-bis btn-lg" %>
        </p>
      <% end %>

      <div class="cook-user container text-center padded">
        <div class="row">
          <div class="col-xs-12">
          <% if @cook.user.picture? && @cook.avatar? %>
            <%= cl_image_tag @cook.avatar.path, width: 423, height: 527, quality: 80, fetch_format: :auto, crop: :thumb, gravity: :face, class:"avatar-extra-large" %>
          <% elsif !@cook.user.picture? && @cook.avatar? %>
            <%= cl_image_tag @cook.avatar.path, width: 423, height: 527, quality: 80, fetch_format: :auto, crop: :thumb, gravity: :face, class:"avatar-extra-large" %>
          <% elsif @cook.user.picture? && !@cook.avatar? %>
            <%= image_tag @cook.user.picture, width: 423, height: 527, class:"avatar-extra-large" %>
          <% else %>
            <%= image_tag "chef.jpg", width: 423, height: 527, quality: 80, fetch_format: :auto, crop: :thumb, gravity: :face, class:"avatar-extra-large" %>
          <% end %>

          <h1 class="cook-identity">
          <%= @cook.user.first_name %>
          </h1>
          <h3 class="cook-identity">
            <%= @cook.age %> ans
          </h3>

          </div>
        </div>
      </div>

      <p>&nbsp</p>

      <h2 class="text-center">Ma cuisine</h2>

      <p>&nbsp</p>

      <% @specialities.each do |speciality| %>
        <p>
          Spécialité <span class="label label-default"><%= speciality.name %></span> , niveau <span class="label label-warning"><%= speciality.level %></span>
        </p>
      <% end %>

      <p>&nbsp</p>

      <p>
        " <em><%= @cook.bio %> </em> "
      </p>

      <h2 class="text-center"><%= "#{pluralize_with_0('Adresse', @places.size)} de retrait" %></h2>

      <p>&nbsp</p>

      <% @places.each do |place| %>
        <p>
          <%= place.full_place %> <span class="label label-default"><%= place.kind_of_place %></span>
          <% if place.active %>
            <span class="label label-warning">Adresse active</span>
          <% end %>
        </p>
      <% end %>

      <p>&nbsp</p>

      <p>
        <%= link_to "Retour aux chefs", cooks_path, class: "btn btn-popote-bis btn-lg" %>
      </p>

    </div>
  </div>

  <div role="tabpanel" class="tab-pane active" id="cook-dishes">
    <div id= "cook-dishes" class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">

        <p>&nbsp</p>

        <% if @cook.user == current_user %>
          <%= link_to "Nouvelle popote", new_cook_dish_path(@cook,@dish), class: "btn btn-popote-bis btn-lg" %></p>
        <% end %>

        <% @dishes.each do |dish| %>

            <div class="dish">
              <div class='dish-upvote'>
                <div class='dish-count'><%= dish.portion_count %></div>
              </div>

              <% if dish.photos? %>

                <%= cl_image_tag dish.photos.first.path, height: 133, width: 200, quality: 80, fetch_format: :auto, crop: :fill, class:"dish-image hidden-xs" %>

              <% else %>

                <%= image_tag "tupperwares.jpg", alt:"Popote", class:"dish-image hidden-xs" %>

              <% end %>

              <div class='dish-body'>

                <h3><%= link_to dish.name, cook_dish_path(@cook,dish) %></h3>

                <p>
                  <span class="label label-default"> <%= dish.kind_of_dish %></span> <%= dish.speciality %><br>
                  <% if dish.portion_count != 0 %>
                  <%= render "countdown", dish: dish %><br>
                  <% else %>
                    <span class="label label-primary"> Épuisé</span><br>
                  <% end %>
                  <h5><%= number_to_currency(dish.price, locale: :fr) %></h5>
                </p>

              </div>

              <% if @cook.user == current_user %>

                <ul class="list-inline dish-controls hidden-sm hidden-xs">
                  <li>
                    <%= link_to edit_cook_dish_path(@cook,dish) do %>
                    <i class="fas fa-pencil-alt"></i>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to cook_dish_path(@cook,dish), method: :delete, data: {confirm: 'Êtes-vous sûr de vouloir supprimer votre popote ?'} do %>
                    <i class="fa fa-trash"></i>
                    <% end %>
                  </li>
                </ul>

              <% elsif dish.exp_date > DateTime.now && dish.portion_count > 0 %>

                <ul class="list-inline dish-controls">
                  <li>
                    <%= render "add_to_cart", cook: @cook, dish: dish %>
                  </li>
                </ul>

              <% else %>

              <% end %>

            </div>
        <% end %>

        <p>
          <%= link_to "Retour aux chefs", cooks_path, class: "btn btn-popote-bis btn-lg" %>
        </p>

      </div>
    </div>
  </div>

  <div role="tabpanel" class="tab-pane" id="orders_r">
    <div id= "orders_r" class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <p class="container text-left">
          Cagnotte <span class="label label-success"><%= number_to_currency(@credit, locale: :fr)%></span>
        </p>
        <% @orders_r.each do |o_r| %>
          <% if !o_r.nil? %>
            <hr>
            <p>
              <%= "Le #{o_r.created_at.strftime('%d/%m/%Y à %H:%M')} :" %><br>
            </p>
            <p>
              Commande de
              <%# if !@user.nil? && !@user.cook.nil? %>
                <%#= link_to cook_path(@user.cook) do %>
                  <%#= @user.first_name %>
                <%# end %>
              <%# else %>
                <%= o_r.first_name %>
              <%# end %>
            </p>
            <% o_r.order_items.each do |o_ro_i| %>
              <%= render 'o_ro_i', o_ro_i: o_ro_i, dish: o_ro_i.dish, show_total: true %>
            <% end %>
            <p class="container text-left">
              Total <span class="label label-warning"><%= number_to_currency(o_r.subtotal, locale: :fr) %></span>
              | Frais <span class="label label-warning"><%= number_to_currency(o_r.charge, locale: :fr) %></span>
              | In the pocket <span class="label label-warning"><%= number_to_currency(o_r.in_the_pocket, locale: :fr)%></span>
            </p>
          <% end %>
        <% end %>
       </div>
    </div>
  </div>

  <div role="tabpanel" class="tab-pane" id="orders_p">
    <div id= "orders_p" class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <% @orders_p.each do |o_p| %>
          <% if !o_p.nil? %>
            <hr />
            <p>
              <%= "Le #{o_p.created_at.strftime('%d/%m/%Y à %H:%M')} : " %>
            </p>
            <% o_p.order_items.each do |o_po_i| %>
              <p>
                Commande à
                <%= link_to cook_path(o_po_i.dish.cook) do %>
                  <%= o_po_i.dish.cook.user.first_name %>
                <% end %>
              </p>

              <%= render 'o_po_i', o_po_i: o_po_i, dish: o_po_i.dish, show_total: true %>
            <% end %>
            <p class="container text-left">
              Total payé <span class="label label-warning"><%= number_to_currency(o_p.subtotal, locale: :fr) %></span>
            </p>
          <% end %>
        <% end %>
       </div>
    </div>
  </div>

</div>