config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/about" => "pages#about"
  get "/hygiene" => "pages#hygiene"
  get "/features" => "pages#features"

  resources :cooks do
    resources :dishes, except: [:index]
  end

  resource :cart, only: [:show, :destroy]

  resources :orders, only: [:show, :new, :create]

  resources :order_items, only: [:create, :update, :destroy] do
    member do
      post 'increment'
      post 'decrement'
    end
  end

end

app/views/shared/_cart_text.html.erb
<%= link_to cart_path do  %>
  <div class="badge-container">
    <i class="fas fa-shopping-basket"></i>
    <div class="badge badge-blue"><%= current_cart.total_quantity %></div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">

  <div class="container text-center">

    <div class="flex">

      <div class="footer-section">
        <h3 class="text-center">Nous connaître</h3>
        <div><%= link_to "Quèsaco ?", about_path %></div>
        <div><%= link_to "Comment ça marche ?", features_path %></div>
        <div><%= link_to "Conditions générales d'utilisation" %></div>
        <div><%= link_to "Hygiène et sécurité", hygiene_path %></div>
        <div><%= mail_to "", "Nous écrire" %></div>
        <div><%= link_to "FAQ" %></div>
      </div>

      <div class="footer-section">
        <h3>Nous suivre</h3>
        <div class="footer-section-links">
          <div><%= link_to raw('<i class="fab fa-facebook fa-2x"></i>'), "", target: "blank" %></div>
          <div><%= link_to raw('<i class="fab fa-twitter fa-2x"></i>'), "", target: "blank" %></div>
          <div><%= link_to raw('<i class="fab fa-instagram fa-2x"></i>'), "", target: "blank" %></div>
          <div><%= link_to raw('<i class="fab fa-pinterest fa-2x"></i>'), "", target: "blank" %></div>
        </div>
      </div>

    </div>

    <p>© <%= Time.now.year %> laPompeAProtos</p>

  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Left Navigation -->
  <div class="navbar-wagon-left">
    <!-- Logo -->
    <a href="/" class="navbar-wagon-brand">
      <%= image_tag "Logo.png" %>
    </a>
    <!-- Cart basket -->
    <div class="cart-text navbar-wagon-item">
      <%= render 'shared/cart_text' %>
    </div>
    <!-- Text link -->
    <%= link_to "À propos", about_path, class:"navbar-wagon-item navbar-wagon-link hidden-xs" %>
    <%= link_to "Les chefs", cooks_path, class:"navbar-wagon-item navbar-wagon-link btn hidden-xs" %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "Récipients", "/", class:"navbar-wagon-item navbar-wagon-link"%>
    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if user_signed_in? %>
          <% if !current_user.cook.nil? %>
            <% if current_user.provider && current_user.cook.avatar? %>
              <%= cl_image_tag current_user.cook.avatar.path, width: 60, height: 60, crop: :thumb, gravity: :face, class:"avatar-large dropdown-toggle", id:"navbar-wagon-menu", :"data-toggle" => "dropdown" %>
            <% elsif !current_user.provider && current_user.cook.avatar? %>
              <%= cl_image_tag current_user.cook.avatar.path, width: 60, height: 60, crop: :thumb, gravity: :face, class:"avatar-large dropdown-toggle", id:"navbar-wagon-menu", :"data-toggle" => "dropdown" %>
            <% elsif current_user.provider && !current_user.cook.avatar? %>
              <%= image_tag current_user.picture, width: 60, height: 60, class:"avatar-large dropdown-toggle", id:"navbar-wagon-menu", :"data-toggle" => "dropdown" %>
            <% else %>
              <%= image_tag "chef.jpg", class:"avatar-large dropdown-toggle", id:"navbar-wagon-menu", :"data-toggle" => "dropdown" %>
            <% end %>
          <% else %>
            <% if current_user.provider %>
              <%= image_tag current_user.picture, class:"avatar-large dropdown-toggle", id:"navbar-wagon-menu", :"data-toggle" => "dropdown" %>
            <% else %>
              <%= image_tag "default-user.jpg", class:"avatar-large dropdown-toggle", id:"navbar-wagon-menu", :"data-toggle" => "dropdown" %>
            <% end %>
            <!-- Button (call-to-action) -->
            <%= link_to "Devenir Chef", new_cook_path, class:"navbar-wagon-item navbar-wagon-button btn" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% if !current_user.cook.nil? %>
              <li>
                <%= link_to "Mon profil", cook_path(current_user.cook) %>
              </li>
            <% else %>
              <li>
                <%= link_to "Mes commandes", order_path(current_user) %>
              </li>
            <% end %>
            <li>
              <% if !current_user.provider %>
                <%= link_to "Mon compte", edit_user_registration_path %>
              <% end %>
            </li>
            <li>
              <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, data: {confirm: 'Confirmer votre déconnexion ?'} %>
            </li>
          </ul>
        <% else %>
          <!-- Sign in link-->
          <%= link_to "Connexion", new_user_session_path, class:"navbar-wagon-item navbar-wagon-link" %>
          <!-- Button (call-to-action) -->
          <%= link_to "Devenir Chef", new_user_registration_path, class:"navbar-wagon-item navbar-wagon-button btn" %>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Les chefs", cooks_path %></li>
        <% if user_signed_in? %>
          <% if !current_user.cook.nil? %>
            <li><%= link_to "Mon profil", cook_path(current_user.cook) %></li>
          <% else %>
            <li><%= link_to "Mes commandes", order_path(current_user) %></li>
            <li><%= link_to "Devenir Chef", new_cook_path %></li>
          <% end %>
          <li><%= link_to "Récipients", "/" %></li>
          <li><%= link_to "À propos", about_path %></li>
          <li>
            <% if !current_user.provider %>
              <%= link_to "Mon compte", edit_user_registration_path %>
            <% end %>
          </li>
          <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete, data: {confirm: 'Confirmer votre déconnexion ?'} %></li>
        <% else %>
          <li><%= link_to "Les chefs", cooks_path %></li>
          <li><%= link_to "Connexion", new_user_session_path %></li>
          <li><%= link_to "Devenir Chef", new_user_registration_path %></li>
          <li><%= link_to "Récipients", "/" %></li>
          <li><%= link_to "À propos", about_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>