config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/about" => "pages#about"
  get "/hygiene" => "pages#hygiene"
  get "/features" => "pages#features"

  resources :cooks do
    resources :dishes, except: [:index]
  end

  resource :cart, only: [:show, :destroy]

  resources :orders, only: [:show, :new, :create]

  resources :order_items, only: [:create, :update, :destroy] do
    member do
      post 'increment'
      post 'decrement'
    end
  end

end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :order_items, dependent: :destroy

  def add_dish(dish)
    current_item = order_items.find_by(dish_id: dish.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = order_items.build(dish_id: dish.id, quantity: 1)
    end
    current_item
  end

  def total_quantity
    order_items.collect { |oi| oi.valid? ? (oi.quantity) : 0 }.sum
  end

  def subtotal
    order_items.sum { |oi| oi.total_price }
  end
# No charge for customers
  def charge
    subtotal * 0
  end

  def total_amount
    subtotal + charge
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CookCart

  skip_before_action :authenticate_user!

  before_action :set_cart

  before_action :cook_cart, only: [:show]

  def show
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    redirect_to cooks_url, notice: 'Votre panier est vide'
  end

  private
    def set_cart
      @cart = current_cart
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <div class="dish">

      <div class='dish-upvote'>
        <div class="dish-up">
          <%= link_to increment_order_item_path(order_item), method: :post, remote: true do %>
            <i class="fa fa-plus fa-2x"></i>
          <% end %>
        </div>
        <div class='dish_order-count'><%= order_item.quantity %></div>
        <div class="dish-down">
          <%= link_to decrement_order_item_path(order_item), method: :post, remote: true do %>
            <i class="fa fa-minus fa-2x"></i>
          <% end %>
        </div>
      </div>

      <% if dish.photos? %>
        <%= cl_image_tag dish.photos.first.path, height: 117, width: 175, quality: 80, fetch_format: :auto, crop: :fill, class:"dish-image hidden-xs" %>
      <% else %>
        <%= image_tag "tupperwares.jpg", alt:"Popote", class:"dish-image hidden-xs" %>
      <% end %>

      <div class='dish-body'>
        <h3><%= dish.name %></h3>
        <p>Prix : <%= number_to_currency(order_item.unit_price, locale: :fr) %></p>
        <h5>
          Sous-total : <%= number_to_currency(order_item.total_price, locale: :fr) %>
        </h5>
      </div>
      <div class="dish-details">
        <h5>Rendez-vous</h5>
        <p>
          <% dish.cook.places.each do |place| %>
            <% if place.active %>
              <%= place.full_address %><br>
              <%= "#{place.zip_code} #{place.city}" %><br>
            <% end %>
          <% end %>
          <span class="label label-primary"><%= dish.collect_date.strftime('%d/%m/%Y %H:%M') %></span>
        </p>
      </div>

      <ul class="list-inline dish-controls">
        <li>
          <%= link_to order_item, data: { confirm: "Êtes-vous sûr de vouloir supprimer la popote '#{order_item.dish.name}' de votre panier ?" }, method: :delete, remote: true do %>
          <i class="fa fa-trash"></i>
          <% end %>
        </li>
      </ul>

    </div>
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<div class="flash"></div>

<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @order_items.size == 0 %>

  <div class="padded text-center">
    <p>
      Votre panier est vide...<br>
      <%= link_to "Retour", root_path, class:"btn btn-popote btn-lg" %>
    </p>
  </div>

<% else %>

  <div class="container padded text-left">
    <%= link_to "Ajouter une popote", cooks_path, class: 'btn btn-popote-bis' %> <%= link_to "Vider mon panier", @cart, method: :delete, data: {confirm: 'Sûr de vouloir vider votre panier ?'}, class: "btn btn-popote-bis" %>
  </div>

  <% @order_items.each do |order_item| %>

    <div class="cart-<%= order_item.id %>">
      <%= render 'carts/cart_row', order_item: order_item, dish: order_item.dish, show_total: true %>
    </div>

  <% end %>

  <div class="total-cart">
    <%= render 'carts/total_cart', cart: @cart %>
  </div>

<% end %>

app/views/carts/_total_cart.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <p>
          Montant à payer <span class="label label-warning"><%= number_to_currency(cart.total_amount, locale: :fr)%></span>
        </p>
        <hr />
        <p>
          <%= link_to "Valider", new_order_path, class: "btn btn-popote btn-lg" %>
        </p>
    </div>
  </div>
</div>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>